README.md

Add instructions on how to use this repo for creating and serving Helm charts.

[DM-17979] 

---

index.yaml

Must have been indexed at the wrong time, 0.8.9 isn't in the list,
so this is a problem.

[DM-25725] Fix index.yaml

---

charts/kafka-aggregator/.helmignore
charts/kafka-aggregator/Chart.yaml
charts/kafka-aggregator/templates/NOTES.txt
charts/kafka-aggregator/templates/_helpers.tpl
charts/kafka-aggregator/templates/init-example.yaml
charts/kafka-aggregator/templates/producer.yaml
charts/kafka-aggregator/templates/worker.yaml
charts/kafka-aggregator/values.yaml

- Add a deployment for the `kafka-aggregator` worker and producer
- Add a job for the `kafka-aggreatator` example initialization

[DM-25485] Implement kafka-aggregator Helm chart

---

charts/neophile/Chart.yaml
charts/neophile/README.md
charts/neophile/templates/_helpers.tpl
charts/neophile/templates/configmap.yaml
charts/neophile/templates/cronjob.yaml
charts/neophile/templates/vault-secret.yaml
charts/neophile/values.yaml

This will run periodically in Roundtable to look for needed
dependency updates in our repositories.

[DM-25844] Add new chart for neophile

---

.github/workflows/ci.yaml
charts/cadc-tap-postgres/Chart.yaml
charts/cadc-tap-postgres/values.yaml
charts/cadc-tap/Chart.yaml
charts/cadc-tap/values.yaml
charts/fileserver/Chart.yaml
charts/firefly/Chart.yaml
charts/firefly/values.yaml
charts/gafaelfawr/Chart.yaml
charts/kafka-aggregator/Chart.yaml
charts/kafka-aggregator/values.yaml
charts/kafka-connect-manager/Chart.yaml
charts/kafka-connect-manager/values.yaml
charts/landing-page/Chart.yaml
charts/mobu/Chart.yaml
charts/neophile/Chart.yaml
charts/nublado/Chart.yaml
charts/nublado/values.yaml
charts/opendistro-es/Chart.yaml
charts/opendistro-es/values.yaml
charts/postgres/Chart.yaml

Use helm/chart-testing-action to lint all Helm charts on all
pushed branches.

[DM-25975] Add Helm linting for all charts

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/redis-deployment.yml

This is a parameter for the spec of the Deployment, not a parameter
for the Container.

[DM-25766] Fix placement of restartPolicy for Gafaelfawr

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/redis-deployment.yaml

This is not supported until Kubernetes version 1.18.

[DM-26412] Remove fsGroupChangePolicy from Gafaelfawr Redis

---

charts/squash-api/.helmignore
charts/squash-api/Chart.yaml
charts/squash-api/templates/NOTES.txt
charts/squash-api/templates/_helpers.tpl
charts/squash-api/templates/deployment.yaml
charts/squash-api/templates/ingress.yaml
charts/squash-api/templates/redis-deployment.yaml
charts/squash-api/templates/redis-service.yaml
charts/squash-api/templates/service.yaml
charts/squash-api/templates/worker-deployment.yaml
charts/squash-api/values.yaml

- Flask app (API) deployment and service 
- Celery worker deployment
- Redis deployment and service
- Ingress configuration for using cert-manager and lets encrypt tls
- Review pod hardening configuration

[DM-26455] Implement a Helm chart for the SQuaSH API

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/values.yaml

Install 1.4.1 instead of 1.4.0.

[DM-26682] Bump Gafaelfawr version

---

charts/nublado/Chart.yaml
charts/nublado/templates/jupyterhub/clusterrole.yml
charts/nublado/templates/jupyterhub/deployment.template.yml
charts/nublado/templates/prepuller/cronjob.template.yml
charts/nublado/templates/reaper/cronjob.template.yml

Pull the username and password out of a vault secret.

[DM-26158] Registry username and password

---

charts/nublado2/Chart.yaml
charts/nublado2/templates/nublado-config.yaml
charts/nublado2/values.yaml

Breaking out hub config and nublado config and being more consistent
about naming.

[DM-27245] Nublado2 config refactor

---

charts/cachemachine/.helmignore
charts/cachemachine/Chart.yaml
charts/cachemachine/templates/NOTES.txt
charts/cachemachine/templates/_helpers.tpl
charts/cachemachine/templates/clusterrole.yml
charts/cachemachine/templates/clusterrolebinding.yml
charts/cachemachine/templates/deployment.yaml
charts/cachemachine/templates/ingress.yaml
charts/cachemachine/templates/role.yaml
charts/cachemachine/templates/rolebinding.yaml
charts/cachemachine/templates/service.yaml
charts/cachemachine/templates/serviceaccount.yaml
charts/cachemachine/templates/tests/test-connection.yaml
charts/cachemachine/templates/vault-secrets.yaml
charts/cachemachine/values.yaml

Initial chart for the cachemachine to pull images.

[DM-27441] Cachemachine chart

---

charts/nublado2/Chart.yaml
charts/nublado2/templates/nublado2-vault-secret.yaml
charts/nublado2/values.yaml

Improve charts to use vault-secrets-operator and pull more things into the default values.yaml.

[DM-27441] Nublado2: vault-secrets usage

---

charts/squash-api/Chart.yaml
charts/squash-api/templates/deployment.yaml
charts/squash-api/templates/worker-deployment.yaml
charts/squash-api/values.yaml

Update app version and other fixes.

[DM-27918] Fix SQuaSH docker build

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/ingress-token.yaml

Make this point to the local service to get the ok if your token
is set when asking for the token UI.

[DM-28043] Token ingress auth-url

---

charts/cadc-tap/Chart.yaml
charts/cadc-tap/templates/mock-qserv-deployment.yaml

This was placed in the wrong place.

[DM-28454] Fix block conditional in TAP chart

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

[DM-28950] Get rid of podcmd

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Got one version ahead of myself.  Off by one errors are the second
leading cause of errors.

[DM-29112] Fix nublado2 version

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/ingress-token.yaml
charts/gafaelfawr/templates/ingress.yaml

paths is a subkey of http, not at the same level.

[DM-29085] Fix indentation error in Gafaelfawr ingress

---

charts/squareone/.helmignore
charts/squareone/Chart.yaml
charts/squareone/README.md
charts/squareone/templates/NOTES.txt
charts/squareone/templates/_helpers.tpl
charts/squareone/templates/configmap.yaml
charts/squareone/templates/deployment.yaml
charts/squareone/templates/hpa.yaml
charts/squareone/templates/ingress.yaml
charts/squareone/templates/service.yaml
charts/squareone/templates/serviceaccount.yaml
charts/squareone/templates/tests/test-connection.yaml
charts/squareone/values.yaml

This is the initial creation of the chart for Squareone, the landing page app for Rubin Science Platform (https://github.com/lsst-sqre/squareone). The initial version is 0.1.0.

DM-29432: Squareone v 0.1.0 chart

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

We're folding in all the options form parts into the lower level,
and adding a leading 0 because there's trickiness I think with the
parsing and figuring out if it's a string or a float if it's a leading
zero.  Or at least I think I've had problems like this before.

[DM-29532] Update chart for refactors

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/ingress-token.yaml
charts/gafaelfawr/templates/ingress.yaml

networking.k8s.io/v1 has significant changes to the YAML spec, so
just changing the apiVersion isn't enough.  Add another conditional
to choose between the old and new format for the paths.

[DM-28120] Fix Gafaelfawr ingress for v1 version

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/ingress-rewrite.yaml

The rewrite ingress needs a unique name.

[DM-28120] Fix duplicate Gafaelfawr ingress name

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/ci/values-idfdev.yaml
charts/gafaelfawr/templates/serviceaccount-tokens.yaml
charts/gafaelfawr/templates/serviceaccount.yaml

- Fix syntax errors in the `ClusterRole` and the service account workload identity binding
- Add another values file for hopefully better linting

[DM-28120] Fix chart syntax errors, add more linting

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/serviceaccount-tokens.yaml

Another syntax error not caught by helm lint.

[DM-28120] Fix Gafaelfawr ClusterRoleBinding

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/configmap.yaml
charts/gafaelfawr/templates/post-install-init.yaml

- Fix ordering of Gafaelfawr post-install hooks
- Fix the Gafaelfawr issuer.aud configuration

[DM-28120] Fix post-install ordering, Gafaelfawr config

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/ingress-rewrite.yaml
charts/gafaelfawr/values.yaml

- Use a version of the Cloud SQL sidecar with a shell for the termination trick
- Avoid a redirect in the Gafaelfawr redirect ingress

[DM-28120] Fix Gafaelfawr redirect ingress, Cloud SQL sidecar

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/serviceaccount-tokens.yaml

Forgot to update the name of the cluster role in the binding.

[DM-28120] Fix Gafaelfawr tokens cluster role binding

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/post-install.yaml
charts/gafaelfawr/templates/serviceaccount-tokens.yaml

- Add the create verb to the ClusterRole
- Fix the name of the post-install hook job

[DM-28120] Fix Gafaelfawr ClusterRole

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/templates/configmap.yaml

The conditional in the ConfigMap was checking a condition that is
now always true.  Check for the clientId setting instead.

[DM-28120] Fix Gafaelfawr CILogon support

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Fixes a bug in parsing cachemachine results at NCSA.

[DM-28120] Update nublado2 to 1.1.2

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Picks up a fix for talking to cachemachine.

[DM-28120] Bump nublado2 version to 1.1.3

---

charts/cadc-tap/Chart.yaml
charts/cadc-tap/templates/mock-qserv-deployment.yaml
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/templates/tap-schema-db-deployment.yaml
charts/cadc-tap/templates/uws-db-deployment.yaml
charts/cadc-tap/values.yaml

This will let us set it to don't pull for minikube.

[DM-29696] TAP: Allow configuration of pull policy

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Removes legacy code for Gafaaelfawr 1.x and fixes asyncio and
ordering problems with the new user resource creation code.

[DM-30007] Deploy version 1.2.1 of nublado2

---

charts/exposurelog/Chart.yaml
charts/exposurelog/values.yaml

and change default pull policy to Always

exposurelog: use version 0.4.0

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

It's too small to be of any use.

Remove Tiny instance size from default list

---

charts/squareone/Chart.yaml

Includes updates from https://github.com/lsst-sqre/squareone/pull/21

DM-30839: Update squareone chart to 0.2.0

---

charts/cadc-tap/Chart.yaml
charts/cadc-tap/templates/tap-deployment.yaml
charts/cadc-tap/values.yaml
charts/tap-schema/.helmignore
charts/tap-schema/Chart.yaml
charts/tap-schema/templates/_helpers.tpl
charts/tap-schema/templates/tap-schema-db-deployment.yaml
charts/tap-schema/templates/tap-schema-db-service.yaml
charts/tap-schema/values.yaml

And allow the cadc-tap chart to get a URL to connect
to it.

[DM-30753] Create tap-schema chart

---

charts/squareone/Chart.yaml

Includes a typo fix for the terms of service.
https://github.com/lsst-sqre/squareone/pull/23

DM-30887: Update Squareone to 0.2.2

---

charts/tap-schema/Chart.yaml

Picks up new changes from Gregory.

Bump default version of tap-schema

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Add pull secret to both Lab pod deployment and user namespace serviceaccount

Add pull_secret_path

---

charts/mobu/Chart.yaml
charts/mobu/README.md

Install the new 2.1.1 release.

Bump version of mobu

---

charts/squareone/Chart.yaml

This release includes revised footer text.

DM-31197: Squareone version 0.3.1 (chart and app)

---

charts/mobu/Chart.yaml
charts/mobu/README.md

New Slack formatting changes and a few additional bug fixes.

[DM-31273] Bump mobu version to 2.2.0

---

charts/mobu/Chart.yaml
charts/mobu/README.md

[DM-31201] Bump version of mobu

---

charts/squareone/Chart.yaml
charts/squareone/values.yaml

This chart / app version provides integration with the semaphore service.

Create squareone chart 0.4.0

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Picks up fixes for race conditions when creating or deleting labs
and fixes to make Kubernetes calls async.

[DM-31418] Update version of nublado2

---

charts/mobu/Chart.yaml
charts/mobu/README.md

[DM-31406] Bump mobu version

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/README.md

Pick up dependency updates and fixes to the token management process.

[DM-31387] Bump version of Gafaelfawr

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Pick up fix to namespace deletion during lab shutdown.

[DM-31504] Bump version of nublado2

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

See: https://kubernetes.dask.org/en/latest/kubecluster.html#role-based-access-control-rbac

Expand permissions required for Dask

---

charts/nublado2/Chart.yaml
charts/nublado2/templates/clusterrole.yml

(also delete weirdly duplicated rules: entry)

Give nublado2 podddisruptionbudgets rules to grant to lab pods for dask

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

This seems to cause some kind of problem starting from scratch
in the minikube environment, and I don't think we use this part
of the chart.

[DM-31947] Turn off the user scheduler

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Okay let's turn off user placeholder as well.

[DM-31947] Nublado2 chart 0.5.2

---

charts/cadc-tap/Chart.yaml
charts/cadc-tap/values.yaml

This should get datalink finished up.

[DM-32418] Point to new datalink version and app version

---

charts/kafka-connect-manager/Chart.yaml
charts/kafka-connect-manager/README.md
charts/kafka-connect-manager/templates/s3_sink.yaml
charts/kafka-connect-manager/values.yaml

- Add `store.url` to the S3 Sink configuration

[DM-32486]  Make Amazon S3 Sink connector work with other S3 providers

---

charts/strimzi-registry-operator/Chart.yaml
charts/strimzi-registry-operator/crds/registry.yaml
charts/strimzi-registry-operator/values.yaml

Incorporates changes in https://github.com/lsst-sqre/strimzi-registry-operator/pull/8, already reviewed

strimzi-registry-operator: Upgrade to v0.3.0 of app

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Pick up fix for authentication token refresh.

[DM-32551] Update nublado2 to 1.4.2

---

charts/kafka-connect-manager/Chart.yaml
charts/kafka-connect-manager/README.md
charts/kafka-connect-manager/templates/mirrormaker2.yaml
charts/kafka-connect-manager/templates/s3_sink.yaml
charts/kafka-connect-manager/values.yaml

- Add `s3.part.size` configuration

[DM-32006] Enable Parquet connector at LDF EFD

---

charts/plot-navigator/Chart.yaml

Maybe this is the last bugfix?

Bump plot-navigator.

---

charts/mobu/Chart.yaml
charts/mobu/README.md

Lots of various bug fixes, mostly to better error reporting but
also allow for larger responses from WebSockets and redo how the
Docker image is built.

[DM-32556] Bump version of mobu

---

charts/nublado2/Chart.yaml
charts/nublado2/values.yaml

Pick up fix for internal auth between lab and hub.

[DM-32755] Bump version of nublado2

---

charts/alert-stream-schema-registry/Chart.yaml
charts/alert-stream-schema-registry/values.yaml

Use the common lsstdm repository instead of my personal repo

DM-32744: update alert-stream-schema-registry container location

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/README.md

Deploy the new version that uses async SQLAlchemy.

[DM-32595] Bump version of Gafaelfawr

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/README.md

Pick up fix for database initialization.

[DM-32899] Bump version of Gafaelfawr

---

charts/alert-stream-simulator/Chart.yaml
charts/alert-stream-simulator/templates/kafka-topics.yaml

Quotes make things strings, but I need ints.

DM-32958: alert-stream-simulator: fix up types when creating topic

---

charts/alert-stream-broker/Chart.yaml
charts/alert-stream-broker/templates/kafka.yaml

This fixes specification of pod affinity and tolerations for strimzi in v1beta2; the docs I had read were out of date.

alert-stream-broker: fix pod affinity and tolerations

---

charts/moneypenny/Chart.yaml
charts/moneypenny/README.md
charts/moneypenny/templates/deployment.yaml
charts/moneypenny/templates/serviceaccount.yaml
charts/moneypenny/values.yaml

Fix typos and syntax errors caught by Phalanx testing.

[DM-32811] Fix errors in moneypenny chart

---

charts/alert-database/Chart.yaml
charts/alert-database/templates/ingester-serviceaccount.yaml

Very confused that this wasn't caught in CI....

DM-32643: Fix syntax of metadata annotation

---

charts/gafaelfawr/Chart.yaml
charts/gafaelfawr/README.md

Pick up fix for Kubernetes object creation.

[DM-33121] Bump version of Gafaelfawr

---

charts/noteburst/Chart.yaml
charts/noteburst/templates/configmap.yaml

For deployment as noteburst 0.2.0-alpha.2

DM-33025: Improve templating of NOTEBURST_REDIS_URL

---

charts/sherlock/Chart.yaml

Roll out a new version to help with front end developing.

[DM-33338] Sherlock 0.1.2

---

rsp-starter/templates/ingress.yaml

@r-owen spotted this; might be a hold-over from a refactoring?

Drop extra end tag from ingress template

---

charts/times-square/Chart.yaml
charts/times-square/README.md
charts/times-square/templates/configmap.yaml
charts/times-square/templates/deployment.yaml
charts/times-square/templates/gafaelfawrtoken.yaml
charts/times-square/templates/ingress.yaml
charts/times-square/templates/vault-secret.yaml
charts/times-square/values.yaml

Update the times-square support with an embedded redis (via a sub-chart) and with SQL support via Cloud SQL.

DM-33627: Update times-square with Redis and SQL support

---

charts/times-square/Chart.yaml
charts/times-square/README.md
charts/times-square/templates/_helpers.tpl

DM-33627: Add times-square.serviceAccountName function

---

charts/neophile/Chart.yaml

Pick up change to setting automerge.

[DM-33830] Bump neophile version

---

charts/times-square-ui/Chart.yaml
charts/times-square-ui/README.md
charts/times-square-ui/templates/networkpolicy.yaml

This must match the container port, rather than the service's port.

DM-33930: Fix network policy port

---

charts/mobu/Chart.yaml
charts/mobu/README.md
charts/mobu/values.yaml

Switch to GitHub Container Registry as the canonical image source.
Fix some comments in values.yaml.

[DM-33813] Update mobu chart for 4.2.0 release

---

charts/portal/Chart.yaml
charts/portal/README.md
charts/portal/templates/service.yaml
charts/portal/values.yaml

There was a stray space in the service type.  Also get rid of
unused values settings.

[DM-26506] Fix Portal service definition

---

charts/cadc-tap-postgres/Chart.yaml
charts/cadc-tap-postgres/README.md
charts/cadc-tap-postgres/templates/tap-deployment.yaml

Remove an unterminated quote mark and fix one values reference.

[DM-26506] Fix options for cadc-tap-postgres

---

charts/tap-schema/Chart.yaml

This includes new changes for DP0.2.

[DM-34111] Deploy new scm_schemas version

---

charts/datalinker/Chart.yaml
charts/datalinker/templates/deployment.yaml
charts/datalinker/templates/vault-secrets.yaml
charts/datalinker/values.yaml

This should add the butler secret and docker pull secret
and puts them on the container.

[DM-34737] Mount butler secret

---

charts/datalinker/Chart.yaml
charts/datalinker/templates/deployment.yaml
charts/datalinker/values.yaml

Default ingress class to nginx.
Fix secret name files to include extensions.

[DM-34737] Datalinker chart fixes

---

charts/strimzi-registry-operator/Chart.yaml
charts/strimzi-registry-operator/README.md

DM-35597: Create 2.0.0 release of strimzi-registry-operator

---

charts/redis/Chart.yaml
charts/redis/templates/networkpolicy.yaml

I messed up the syntax in the original version and didn't expand the template as I had intended.

DM-37390: Fix Redis NetworkPolicy label

---

charts/strimzi-registry-operator/Chart.yaml
charts/strimzi-registry-operator/README.md

Use strimzi-registry-operator 0.7.1

Bump chart version to 2.1.3
