.github/workflows/release.yaml
The chart release action is not correctly detecting the last tag,
which appears to be due to a Git behavior change.  Try using an
old version of Ubuntu to see if that works around the problem.
=> [DM-25393] Run the action on an older Ubuntu

.github/workflows/release.yaml
checkout now does shallow clones by default, which breaks the
logic for finding changes since the previous tag.  Disable that.
=> [DM-25393] Don't use shallow clones for release action

.github/workflows/ci.yaml, .gitignore, tests/requirements.txt, tests/version_test.py
Add a test that any modified Helm charts have had their version
updated since the previous release.  Run that on all pushed
branches so that it will test pull requests.
=> [DM-25393] Check for Helm chart version updates

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/values.yaml
This allows someone with that scope to create an access token that
also has that scope, which is required by mobu.  We will want to
revisit this when we have a more comprehensive identity management
plan.
Remove unnecessary quotes from appVersion in the Gafaelfawr chart.
=> Add exec:admin to the Gafaelfawr known scopes

charts/neophile/Chart.yaml, charts/neophile/templates/cronjob.yaml
The template was copied from a Deployment, but a CronJob has a
different structure and requires more indentation.
=> [DM-25844] Fix indentation of labels in neophile chart

charts/neophile/Chart.yaml, charts/neophile/templates/cronjob.yaml
This turns out to be a required field because the default for a
Job isn't valid for a CronJob.
=> [DM-25844] Add restartPolicy to neophile CronJob

charts/neophile/Chart.yaml, charts/neophile/templates/configmap.yaml, charts/neophile/values.yaml
Add github_email to the values.yaml file and the ConfigMap template.
=> [DM-25844] Add neophile support for github_email parameter

renovate.json
We don't need to get the pull requests as soon as a new release
happens.  This aligns with Monday being the day that we merge
third-party dependency updates.
=> Set a weekly schedule for Renovate

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/templates/redis-deployment.yml, charts/gafaelfawr/values.yaml
Since we're giving users a shell into the Kubernetes private
network, add password protection to Gafaelfawr's Redis for an
additional layer of protection.
Change the pull policy for the Gafaelfawr image to IfNotPresent
since we're pulling tagged images and the tag won't move.  Users
that override this to point to a ticket branch can also override
the pull policy.
=> [DM-26078] Add Gafaelfawr support for password-protected Redis

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/redis-deployment.yml
Every thirty seconds, make sure that Redis can write to its
database.  This will catch problems we've seen in the past where
the NFS mount for the persistent volume goes read-only due to NCSA
disk issues.  If that happens with this probe, the container will
be killed and restarted, which is the correct action to take to
recover.
Set the restart policy to OnFailure to allow for this restart.
=> [DM-25766] Add a Redis liveness probe

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/values.yaml
Add configuration settings for InfluxDB token issuance and for
the OpenID Connect server to support Chronograf, both disabled
by default.
=> [DM-26072] Add Gafaelfawr support for InfluxDB and Chronograf

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/redis-deployment.yml
Despite the implication of the Kubernetes documentation, this setting
is not truly supported.  Deployments only allow it to be set to Always.
Just remove it entirely and hope the default behavior is correct.
=> [DM-25766] Remove restartPolicy for Gafaelfawr

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/deployment.yaml, charts/gafaelfawr/templates/redis-deployment.yaml, charts/gafaelfawr/templates/redis-networkpolicy.yaml
Add hardening configuration to the Gafaelfawr main deployment and
Redis deployment:
- Specify runAsUser, runAsGroup, and runAsNonRoot
- Disable Kubernetes service account tokens
- Disable privilege escalation
- Disable all capabilities
- Enable read-only file systems
- For Redis, specify an fsGroup and fsGroupChangePolicy
Also add a NetworkPolicy for the Redis deployment that only allows
incoming connections from the Gafaelfawr pod and no outbound
connections.
Rename redis-deployment to end in .yaml rather than .yml for
consistency.
=> [DM-26412] Add security hardening for Gafaelfawr

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/redis-deployment.yaml
All of a sudden, the limit is being copied to the request, which
is excessive since we don't need a full CPU.  Override this with
a small request.
=> [DM-26412] Set a request for Gafaelfawr Redis CPU

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/redis-networkpolicy.yaml
The app tag was set on the deployment but not the pod.  Select by
name instead of app.
=> [DM-26412] Fix Gafaelfawr NetworkPolicy pod selector

charts/nublado/Chart.yaml, charts/nublado/templates/jupyterhubproxy/ingress.template.yml, charts/nublado/values.yaml
For the base and summit clusters, we're not going to run the ingress
or the cert-manager installation.  Those instead will be handled by
IT.  However, the default cluster issuer will be configured for
lsst.org, rather than for our lsst.codes hostnames.
Add support to the nublado chart for configuring TLS for the hostname
used by the JuptyerHub proxy ingress.  ingress-nginx should then
merge that TLS configuration with all other ingress configurations
for the same hostname that don't specify a TLS configuration, which
is all of them at present.  That should accomplish the goal of using a
separate certificate issuer for the nublado hostname.  That issuer
will be set up by lsp-deploy.
Take the issuer name and the secret name as configuration settings in
values.yaml.
=> [DM-25487] Add TLS configuration to nubaldo ingress

charts/nublado/Chart.yaml, charts/nublado/templates/jupyterhubproxy/ingress.template.yml, charts/nublado/values.yaml
Use cluster_issuer, not issuer, and secret, not secret_name,
consistently in values.yaml and in the template.
=> [DM-25487] Fix values naming for nublado TLS configuration

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/values.yaml
Add an option to the Gafaelfawr Helm chart to force the InfluxDB
username to a specific value.
=> [DM-26682] Add Gafaelfawr option to set InfluxDB username

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/values.yaml
Pick up the new Gafaelfawr release and bump the chart version
accordingly.
=> [DM-26682] Bump Gafaelfawr version to 1.5.0

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/ingress.yaml
Gafaelfawr now supports exposing configuration information for its
OpenID Connect provider.  Conditionally add that to the ingress if
the OpenID Connect provider is enabled.
=> [DM-26602] Add openid-configuration endpoint to Gafaelfawr

charts/nublado2/Chart.yaml, charts/nublado2/requirements.yaml, charts/nublado2/templates/_helpers.tpl, charts/nublado2/templates/nublado-config.yaml, charts/nublado2/values.yaml
Okay, so now we're basing a nublado2 initial chart on top of the
zero-to-jupyterhub chart as a subchart.  I'm not overriding the
jupyterhub_config.py, which means we're setting a couple other
things, and probably some I don't know or understand, but we'll
cross that bridge when we come to it.  This at least gets things
going, and the values.yaml configures the subchart with proper
UID/GID and the python that loads in the nublado2 library to
set up additional config.
I know the requirement is a bit janky, but this build contains
specific security configuration improvements to allow us to
just put the uid / gid yaml in directly.  We can update this as we
go, but we should test each update carefully since it is also
a code / functionality update.
=> [DM-27044] Nublado2 chart initial commit

charts/kafdrop/.helmignore, charts/kafdrop/Chart.yaml, charts/kafdrop/templates/NOTES.txt, charts/kafdrop/templates/_helpers.tpl, charts/kafdrop/templates/deployment.yaml, charts/kafdrop/templates/ingress.yaml, charts/kafdrop/templates/service.yaml, charts/kafdrop/values.yaml
Kafdrop is a web UI for viewing Kafka topics and browsing consumer groups. This PR adds the Kafdrop chart temporarily in our charts repo because I couldn't find Kafdrop in any other public helm chart repo. There's a standing [PR](https://github.com/obsidiandynamics/kafdrop/pull/114) in the Kafdrop GitHub repo to add github actions to publish the helm chart. When that PR is merged the plan is to use their helm chart repo instead and remove this chart from ours.
=> [DM-27274] Add kafdrop chart

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
- Configure the new Gafaelfawr authenticator for nublado2
- Remove the `fsGroup` setting since it requires Kubernetes 1.19
- Add ingress configuration for nublado2 (except for the parts that are environment-specific)
- Enable authentication state storage for nublado2 (used by Gafaelfawr)
- Add a NetworkPolicy to allow the nginx ingress to talk to the JupyterHub proxy
=> [DM-27278] Add Gafaelfawr authenticator to nublado2

charts/nublado2/Chart.yaml, charts/nublado2/templates/clusterrole.yml, charts/nublado2/templates/clusterrolebinding.yml
This gives the hub role a lot more things it can do.  We need to be
able to use a clusterrole to create namespaces and watch pods in
other namespaces, so we'll need this for the multinamespace work.
This is also required to create any kubernetes objects from the
hub, so the arbitrary resource creation objects have to be of
types that can be created by the hub, otherwise you get a 403.
The list of roles comes from what is currently on nublado, so we
can trim it down, or keep it here and trim it once we get other
parts working.
Note that the clusterrolebinding binds to the service account that
the subchart creates.
=> [DM-27245] Nublado2 clusterrole

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
This will stop us from defaulting to the ugly tree view.  This
is also how nublado v1 works, so this is needed to make mobu
happy.
=> [DM-27353] Nublado2: default to lab

charts/exposurelog/Chart.yaml, charts/exposurelog/templates/deployment.yaml
- / returns 404, /exposurelog returns 400. Use a simple query for the
liveness/readiness path
=> Fix liveness and readiness probes

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Turn off the prepuller in the helm chart.  It doesn't seem to work
in argocd, but it does work on the helm command line...  We don't
use it anyway, so disable it.
=> [DM-27441] Nublado2: turn off prepuller

.github/workflows/ci.yaml, .github/workflows/release.yaml
Depend on only the major version of GitHub actions where possible
to reduce churn from version updates.
=> Relax dependencies on GitHub actions

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/ingress-token.yaml
Using an unqualified gafaelfawr-service.gafaelfawr doesn't work
because nginx uses a Lua DNS library that doesn't honor the search
option in /etc/resolv.conf.
We had previously not used svc.cluster.local because of some issue
on the summit, but inspecting the summit DNS configuration now, it
appears to use cluster.local as its default domain and thus
svc.cluster.local should work.  Return to that configuration,
which will hopefully work on all of our environments.
This problem is temporary since Gafaelfawr 2.0.0 will remove the
need for this annotation in the Gafaelfawr chart (although we'll
still need something similar in the charts of other protected
services).
=> [DM-28227] Fix Gafaelfawr auth-url annotation for tokens

charts/neophile/Chart.yaml, charts/neophile/templates/cronjob.yaml, charts/neophile/values.yaml
Update to 0.2.0 as the default image.  Add a securityContext
configuration to the container and job to drop permissions and
run as non-root.  Disable automount of the Kubernetes service
account token.
=> [DM-28478] Update neophile to 0.2.0, add security config

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Add in an empty list for the other images to show.  Otherwise
nublado2 will get unhappy when showing the options form and trying
to find the default list of images to show.  By default, there is
nothing in there.  But someone could use this list instead of
cachemachine, or merge it with those results.
=> [DM-28482] Nublado2: default empty image list

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
We can now use the same auth-url on all environments, so set it to
the gafaelfawr-service.gafaelfawr.svc.cluster.local URL so that
instantiations don't have to set it.  Pass only the token into
Nublado 2, not other headers, since we'll use an API call to retrieve
the other data.  Add a base_url config setting that has to be
set on all instantiations, which will be used to construct the URL
to contact Gafaelfawr and retrieve token metadata.
=> [DM-28666] Update Nublado 2 auth configuration

charts/cachemachine/Chart.yaml, charts/cachemachine/templates/pull-networkpolicy.yaml, charts/cachemachine/values.yaml
Put the external ingress for cachemachine behind Gafaelfawr to
prevent the Internet from talking to it without authentication.
We will eventually also want to restrict access to it from inside
the cluster, but that's much less important and can be tackled via
a NetworkPolicy later.
Add pod and container hardening best practices from SQR-048, which
should be a no-op for this service since it doesn't do anything
exciting other than answer HTTP requests and make Kubernetes API
calls.
Add a NetworkPolicy that will be used by spawned pods to deny all
network traffic.
=> [DM-28686] Security hardening for cachemachine chart

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
The zero-to-jupyterhub charts normally set the command to
jupyterlab-singleuser, and override what the command is for
the docker container.  If you set cmd = , this means use
the default command for the docker container entrypoint.
This will allow the chart to configure the container command line,
if needed.  Defaulting to the container default.
Unforunately, trying to unset something in a subchart doesn't
seem to work well, or at least, I can't get it to work.  So
I'm adding a new way to set this, which has a default of none,
called pod_cmd.
=> [DM-28482] pod_cmd instead of cmd

charts/cachemachine/Chart.yaml, charts/cachemachine/templates/configmap.yaml, charts/cachemachine/templates/deployment.yaml, charts/cachemachine/values.yaml
Add the configmap that contains JSON files to create preconfigured
cachemachines at startup.
=> [DM-28726] Cachemachine: autostart configmap

charts/nublado2/Chart.yaml, charts/nublado2/templates/netpol.yaml, charts/nublado2/values.yaml
Since the hub and the single user lab pods are running in different
namespaces, we need to modify the hub's network policy in a way
that can't be configured currently.  So just wrap it up into the
nublado2 chart.
=> [DM-28725] Nublado2 network policy

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/values.yaml
Allow setting cilogon.test to true in the Gafaelfawr chart to use
the test instance instead of the primary instance.  Add examples of
CILogon and GitHub configuration.
=> [DM-28845] Support the test CILogon instance in Gafaelfawr

charts/nublado2/Chart.yaml, charts/nublado2/templates/netpol.yaml
We're more worried about ingress than egress.  For now let's
disable egress.  This allows the hub to contact everyone on the
internet.
=> [DM-28923] Nublado2: get rid of egress policy

charts/neophile/Chart.yaml, charts/neophile/templates/cronjob.yaml
Bump the version of neophile to 0.2.1 and mark the root file system
of the cron job container as read-only.
=> [DM-28993] Bump neophile version, add more hardening

charts/cachemachine/Chart.yaml, charts/cachemachine/values.yaml
Our GitHub Actions machinery doesn't set the latest tag, so using
that in the deployment doesn't work well.  Pin to the latest version
and reflect that in the appVersion field of Chart.yaml.
=> [DM-28993] Set version of cachemachine Docker image

.github/workflows/ci.yaml
- Install Python 3.8
- Change the way the lint action is kicked off
=> Fix CI configuration for helm/chart-testing-action

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
These are the default resources that we expect for the container,
so things like the service account, namespace, and other things
that need to be created, but can be overridden per environment.
=> [DM-29112] Nublado2: add in default resources to chart

charts/neophile/Chart.yaml, charts/neophile/templates/configmap.yaml
This returns the value that is marked as required, so it's supposed
to be used in a pipeline where that value is used, not at the top
of the chart.
=> [DM-29329] Fix syntax of required function

charts/neophile/Chart.yaml, charts/neophile/templates/configmap.yaml
Fix bug introduced in 0.2.4 when fixing the required function that
collapsed too much whitespace.
=> [DM-29329] Fix whitespace bug in the neophile chart

charts/neophile/Chart.yaml, charts/neophile/templates/cronjob.yaml
Create a writable home directory for the neophile user since it's
used by pip.  Bump the appVersion to the new 0.2.2 release, which
has a fix for GitHub's main vs. master branch change.
=> [DM-29329] Bump neophile version, mount home directory

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Because the stuff in config.user_resources is a list, if you don't do no_sudo like this, it means a huge amount of duplication in the environment values file.
=> Remove pod_uid, force NO_SUDO in lab environment

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/ci/values-default.yaml, charts/gafaelfawr/ci/values-idfprod.yaml, charts/gafaelfawr/ci/values-stable.yaml, charts/gafaelfawr/ci/values-summit.yaml, charts/gafaelfawr/templates/_helpers.tpl, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/templates/deployment.yaml, charts/gafaelfawr/templates/ingress-token.yaml, charts/gafaelfawr/templates/ingress.yaml, charts/gafaelfawr/templates/redis-deployment.yaml, charts/gafaelfawr/templates/redis-networkpolicy.yaml, charts/gafaelfawr/templates/redis-service.yml, charts/gafaelfawr/templates/redis-statefulset.yaml, charts/gafaelfawr/templates/service.yaml, charts/gafaelfawr/templates/vault-secret.yaml, charts/gafaelfawr/values.yaml
- Rework the Helm chart to follow best practices
- Rename resources to remove useless suffixes (keeping both the old and new service for now)
- Restructure `values.yaml` and use camelCase per Helm best practices
- Convert Redis to a `StatefulSet` to avoid volume mount conflicts with persistent volumes
- Add support for persistent volume templates, which we'll use for Redis in the IDF
- Use the new `apiVersion` for `Ingress` resources where appropriate
- Default the image tag to the `appVersion` in the chart
- Pin the version of Redis for smoother upgrade management
- Restart Gafaelfawr pods on configmap changes
=> [DM-29085] Overhaul Gafaelfawr Helm chart

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/ingress-token.yaml
The auth-url link was invalid because it was interpolating the
wrong configuration variable, it was still pointing to the old
service name, and the path was slightly incorrect.
=> [DM-29085] Fix the Gafaelfawr token ingress

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/ci/values-stable.yaml, charts/gafaelfawr/templates/ingress-token.yaml, charts/gafaelfawr/values.yaml
NCSA int (and presumably also stable) cannot resolve the internal
service hostname when used in an auth-url annotation.  Add a
parameter to change it to use the external hostname instead.  (We
can't do this everywhere because it doesn't work with minikube
for other DNS resolution reasons.)
=> [DM-29085] Allow external host for token ingress auth-url

charts/squareone/Chart.yaml, charts/squareone/templates/ingress.yaml, charts/squareone/values.yaml
This chart release fixes issues with the ingress:
- enables ingress by default
- change to a single host name, which also means that the host name can be used correctly to configure the app itself
- ensure the ingress port matches the service port
=> DM-29432: squareone chart 0.1.1

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml
With OpenID Connect, the default redirect_url was incorrect because
it wasn't updated for the change in the values.yaml layout.
=> Fix Gafaelfawr redirect_url construction

charts/firefly/Chart.yaml, charts/firefly/templates/deployment.yaml
Override the current logout setting in the Firefly container,
which is pointing to the old oauth2_proxy URL, to use /logout
instead.
=> [DM-29612] Fix the logout URL for Firefly

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Make things a little cleaner so less of the user resources, volumes, and volume mounts are duplicated between the chart and the configs for the individual environments.  This requires a bit of work from nublado and a bit of cleaning up in the chart, which is here.
=> [DM-29647] Separate automatically created resources and configured ones

charts/moneypenny/Chart.yaml, charts/moneypenny/values.yaml, charts/nublado2/Chart.yaml, charts/nublado2/requirements.yaml, charts/nublado2/values.yaml
Mount the new Gafaelfawr token secret into the hub container as
well.  This means this version of the nublado2 chart can only be
deployed in environments that Gafaelfawr 2.0 has been deployed in.
Unfortunately, because most of the work in the chart is done in
values.yaml, we can't do better than that.
Change the scope used to protect moneypenny.
Change the chart to require Helm 3.  We're already using that
everywhere and know that it works with the upstream chart, even
though the upstream chart is still v1.
=> [DM-28120] Update nublado2 for Gafaelfawr 2.0

charts/mobu/Chart.yaml, charts/mobu/templates/deployment.yaml, charts/mobu/templates/gafaelfawr-secret.yaml, charts/mobu/values.yaml
Provide a new configuration parameter, gafaelfawrSecret, that
specifies the name of a secret in the mobu namespace that will
contain the Gafaelfawr token.  If this is set, do not create the
Gafaelfawr vault secret in the mobu namespace or mount it as a
volume.
Once all installations have switched to Gafaelfawr 2.0, these
portions of the template can be deleted.
Also require Helm v3 for the chart (we're using that everywhere
already) and bump the mobu appVersion in anticipation of the mobu
release with GAFAELFAWR_TOKEN support.
=> [DM-28120] Support new Gafaelfawr secret in mobu

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/cronjob-tokens.yaml, charts/gafaelfawr/templates/deployment.yaml, charts/gafaelfawr/templates/post-install-init.yaml, charts/gafaelfawr/templates/post-install-tokens.yaml
Fix a typo in the command line flag specifying IP address types,
and put the Cloud SQL Auth Proxy container first since it has to
be running before Gafaelfawr can start.
=> [DM-28120] Fix Gafaelfawr Cloud SQL Auth Proxy config

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml
Was missing the scopes key when configuring Kubernetes secrets to
create.
=> [DM-28120] Fix syntax error in Gafaelfawr config map

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/serviceaccount-tokens.yaml
Has to specify secrets, not secret, when granting permissions.
=> [DM-28120] Fix Gafaelfawr cluster role binding

charts/landing-page/Chart.yaml, charts/landing-page/templates/ingress.yaml, charts/landing-page/values.yaml
This is temporary since it will soon be replaced by squareone, but
we need some ingress to take over the TLS configuration from
nublado, and this is the logical choice.
Also require Helm 3, since we're already using that.
=> [DM-28120] Add TLS support to the landing-page chart

charts/postgres/Chart.yaml, charts/postgres/templates/deployment.yml
Currently each database needs a configuration stanza in the postgres
chart.  Add support for a Gafaelfawr database, which we'll use in
the environments without CloudSQL.
=> [DM-28120] Add support for a Gafaelfawr db to postgres

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
I think when we refactored the list of volumes, the normal list of
volumes included a claim.  This prevents the startup.  We were still
doing it wrong before, but since we didn't try to mount the unbound
PVC we got under the radar.
=> [DM-29799] Don't create a pvc for users

charts/squareone/Chart.yaml
Change the default version deployed by squareone to 0.1.3, the
latest release.
=> [DM-28120] Bump appVersion of squareone

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/ingress-rewrite.yaml, charts/gafaelfawr/templates/ingress.yaml
Too much whitespace was being removed in the Kubernetes 1.19 case,
which caused construction of an invalid field.
=> [DM-28120] Fix Gafaelfawr ingress templating

charts/gafaelfawr/Chart.yaml
Picks up a change to cap the number of workers in each pod so that
we don't overrun the connection limit on Cloud SQL databases.
=> [DM-28120] Bump version of Gafaelfawr to 2.0.1

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/ingress-rewrite.yaml, charts/gafaelfawr/templates/ingress.yaml
Use .Capabilities.APIVersion.Has instead of semverCompare, since
the latter apparently didn't work correctly for Kubernetes 1.18.
=> [DM-28120] Fix Gafaelfawr ingress detection

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/ingress-rewrite.yaml, charts/gafaelfawr/templates/ingress.yaml
Argo CD isn't correctly passing data to Helm to execute the
conditional, so temporarily revert to always using the
networking.k8s.io/v1beta1 API version.  This can be reverted when
Argo CD has been upgraded to correctly tell Helm about cluster
capabilities, or once all clusters have been upgraded to
Kubernetes 1.19 or later.
=> [DM-28120] Revert to networking.k8s.io/v1beta1

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/README.md, charts/gafaelfawr/templates/networkpolicy.yaml, charts/gafaelfawr/values.yaml
If enabled, this will restrict access to the Gafaelfawr pod to only
pods in a namespace tagged with gafaelfawr.lsst.io/ingress with a
value of "true".  This will require all cluster access go through
the ingress and will allow hiding of routes by not creating an ingress
for them (the plan is to use this for /auth to prevent users from
minting arbitrary internal and notebook tickets).
=> [DM-28120] Support a NetworkPolicy for Gafaelfawr

charts/firefly/Chart.yaml, charts/firefly/templates/deployment.yaml, charts/firefly/values.yaml
Change appVersion to 2.2.0 and set the default image tag to the
appVersion rather than hard-coding it in values.yaml.  Switch the
chart to Helm v3 (which we're already using to install it in
Science Platform environments).
This chart should be renamed to suit or portal, but that will be
done later as part of a larger overhaul.
=> [DM-28120] Update firefly chart to SUIT 2.2.0

charts/squareone/Chart.yaml, charts/squareone/templates/deployment.yaml
During runtime, the next/image component creates cached versions of
image variants that the app serves. These are stored
in /.next/cache/images. Since we run squareone in a read-only filesystem
for security, the next app isn't able to create and write to this
directory. A solution is to mount an emptyDir at that path. This change
involves an update to the squareone Helm chart.
=> Mount volume for .next/cache/images

charts/squareone/Chart.yaml
This app update includes the ops-era funding text and images.
=> squareone chart 0.1.6, app 0.1.5

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Rather than making the user resource templates a long quoted string,
keep them as YAML.  This allows overriding pieces of the template
from Phalanx, such as the environment variables.
Remove the templating for labels and annotations since it's identical
for every resource and every Kubernetes resource supports labels and
annotations, so they can be added directly in the nublado2 code.
Merge custom resources back in with core resources since nublado2 will
be able to handle this.
=> [DM-30007] Rework lab environment creation

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
These environment variables are per-environment and should only be
set on the IDF, so remove them from the chart.  They will be added
by Phalanx.
=> [DM-30007] Remove Butler environment variables from nublado2

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
This chart can't use appVersion because it's configuring a subchart.
Bump the container version in the correct place.
=> [DM-30007] Bump nublado2 container version

charts/cert-issuer/Chart.yaml, charts/cert-issuer/templates/cluster-issuer.yaml
accessKeyID, not accessKeyId as one would normally expect in Helm.
=> [DM-29926] Fix typo in cert-issuer ClusterIssuer

charts/exposurelog/Chart.yaml, charts/exposurelog/templates/deployment.yaml, charts/exposurelog/values.yaml
I forgot to update the port # and probe URLs. For the latter I think it suffices to use /exposurelog; I tested this by making startup take essentially forever, and by making it fail, and in both cases the URL did not return. However, for the record, one can get the schema using exposurelog/openapi.json (thought I have not been able to find official documentation saying that).
=> DM-30036: exposurelog: update port and probe URLs

charts/cachemachine/Chart.yaml, charts/cachemachine/templates/deployment.yaml
This allows cachemachine to have access to the labels and annotations
of the pod, which are set by other layers like argocd and helm.
=> [DM-30180] Cachemachine mount pod info

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/deployment-tokens.yaml
The CloudSQL support for the token Kubernetes controller was
missing the command: key, and helm lint didn't catch it.
=> [DM-29365] Fix YAML syntax error in Gafaelfawr chart

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/README.md, charts/gafaelfawr/templates/serviceaccount-tokens.yaml
The conditional for whether to create the token management service
account was incorrect.  Remove the obsolete config conditional.
=> [DM-29365] Fix Gafaelfawr token service account creation

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/serviceaccount-tokens.yaml
Apparently when status is a subresource, it gets separate RBAC
permissions.  Add it to the ClusterRole.  Don't worry about being
very precise about what permissions are required for the parent
resource and what permissions are required for the status
subresource; it doesn't seem worth it.
=> [DM-29365] Grant Gafaelfawr access to service token status

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Use gafaelfawr.gafaelfawr instead of gafaelfawr-service.gafaelfawr
so that eventually we can retire the latter.
=> [DM-30064] Update Gafaelfawr URL for nublado2

charts/kafka-connect-manager/Chart.yaml, charts/kafka-connect-manager/README.md, charts/kafka-connect-manager/templates/_helpers.tpl, charts/kafka-connect-manager/templates/influxdb_sink.yaml, charts/kafka-connect-manager/templates/jdbc_sink.yaml, charts/kafka-connect-manager/templates/mirrormaker2.yaml, charts/kafka-connect-manager/templates/s3_sink.yaml, charts/kafka-connect-manager/values.yaml
- Use regex to exclude topics
- Deploy multiple instances of the influxdb-sink connector
=> [DM-30456] Add ability to deploy multiple influxdb-sink connectors in kafka-connect-manager

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/values.yaml
Install Gafaelfawr 3.0.1 and also bump the Google Cloud SQL Auth
Proxy and Redis container versions to their latest releases.
=> [DM-30369] Bump Gafaelfawr image versions

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/README.md
Pick up 3.0.3, which has a fix for issuing of internal and
notebook tokens during race conditions.
=> [DM-30789] Bump version of Gafaelfawr

charts/semaphore/.helmignore, charts/semaphore/Chart.yaml, charts/semaphore/README.md, charts/semaphore/templates/NOTES.txt, charts/semaphore/templates/_helpers.tpl, charts/semaphore/templates/configmap.yaml, charts/semaphore/templates/deployment.yaml, charts/semaphore/templates/hpa.yaml, charts/semaphore/templates/ingress.yaml, charts/semaphore/templates/service.yaml, charts/semaphore/templates/serviceaccount.yaml, charts/semaphore/templates/tests/test-connection.yaml, charts/semaphore/values.yaml
Semaphore is developed at https://github.com/lsst-sqre/semaphore. The app doesn't have any custom functionality yet, but my intention is to demonstrate that the semaphore app can be stood up in a phalanx environment before beginning to develop the backend service itself.
=> DM-30725: Initial chart for the semaphore app

charts/cachemachine/Chart.yaml, charts/cachemachine/templates/ingress.yaml, charts/moneypenny/Chart.yaml, charts/moneypenny/templates/ingress.yaml, charts/squareone/Chart.yaml, charts/squareone/templates/ingress.yaml
We think this was causing warning log lines in the logs, and
so by adding this annotation it should stop that.  For some reason,
it still works even without it.
=> [DM-30974] Add missing nginx-ingress annotation

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/README.md, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/values.yaml
Update Gafaelfawr to the 3.2.0 release and add support for the new
config.errorFooter configuration parameter.
=> [DM-31018] Update to Gafaelfawr 3.2.0, add errorFooter

charts/cachemachine/Chart.yaml, charts/cachemachine/README.md, charts/cachemachine/templates/ingress.yaml, charts/cachemachine/templates/service.yaml
Go back to exposing port 80, since we have other references to
that port.
=> [DM-31082] Fix port of cachemachine service

charts/firefly/Chart.yaml
This is what we're currently running on the IDF and Gregory confirms
it's what we should deploy everywhere for now until there's a new
full release.
=> [DM-30073] Change Firefly default version to suit-233-7-dev

charts/mobu/Chart.yaml, charts/mobu/templates/statefulset.yaml
We only want one mobu running at any given time or they stomp on
each other's labs and wreak havoc.  Convert the Deployment to a
StatefulSet so that the previous running mobu is always stopped
before the new mobu is started.
=> [DM-31201] Convert mobu to a StatefulSet

charts/squareone/Chart.yaml, charts/squareone/templates/configmap.yaml, charts/squareone/values.yaml
- Works with the tickets-DM-30727 image tag of squareone
- Remove broadcastMarkdown
- Add semaphoreUrl config
=> DM-30727: Create squareone 0.4.0-alpha.1

charts/semaphore/Chart.yaml
This release fixes the `/v1/broadcasts` endpoint from showing messages that have `enabled: false` metadata.
=> Update semaphore to 0.2.1

charts/mobu/Chart.yaml
Deploy the new version that supports testing the latest weekly and
integrates with cachemachine rather than requiring hard-coding the
form data for Jupyter spawning.
=> [DM-31490] Bump version of mobu

charts/cachemachine/Chart.yaml
Pick up fix to exclude cordoned nodes from the calculation of which
images are cached.
=> [DM-31529] Bump cachemachine version

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Okay so the issue seems to be while we added the new auth part,
we didn't take out the old auth part, which I think was tripping
over the deprecation warning in the helm chart, causing it to fail.
Since this is a pretty big change and a new version of jupyterhub,
let's just roll this to 0.5.0
=> [DM-31947] Remove old auth stanza, chart to 0.5.0

charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
we do not want singleuser.cloudMetadata.blockWithIptables anywhere.
=> tickets/DM-31959: pathSuffix lets "/nb" (no trailing slash) work again

charts/kafka-connect-manager/Chart.yaml, charts/kafka-connect-manager/README.md, charts/kafka-connect-manager/templates/s3_sink.yaml, charts/kafka-connect-manager/values.yaml
- Create a configmap with the s3-sink connector configuration and use kafkaconnect to upload it
- AWS secrets for the S3 bucket are injected in the environment
=> [DM-32279] Refactor S3 Sink connector in kafka-connect-manager

charts/cadc-tap/Chart.yaml, charts/cadc-tap/values.yaml
Bump chart version, set values.
=> [DM-32418] Use new datalink snippets by default

charts/cert-issuer/Chart.yaml, charts/cert-issuer/README.md, charts/cert-issuer/templates/cluster-issuer.yaml
cert-manager has dropped support for pre-v1 APIs, so update the
API of the ClusterIssuer to v1.  Bump the chart version number to
1.0.0 since it seems to be stable.  Regenerate the documentation.
=> [DM-32422] Update cert-issuer ClusterIssuer API

charts/alert-stream-broker/Chart.yaml, charts/alert-stream-broker/templates/kafka.yaml
The schema for a Kafka resource's storage claims actually uses the key "class", not "storageClassName".
=> DM-32351: alert-stream-broker: Correct the spec for Kafka storage class

charts/cadc-tap/Chart.yaml, charts/cadc-tap/values.yaml
Apparently this chart doesn't automatically push the tag value down.
=> [DM-32418] Bump TAP version

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/values.yaml, charts/vo-cutouts/Chart.yaml, charts/vo-cutouts/README.md, charts/vo-cutouts/templates/_helpers.tpl, charts/vo-cutouts/templates/configmap.yaml, charts/vo-cutouts/templates/deployment-cutout-worker.yaml, charts/vo-cutouts/templates/deployment-db-worker.yaml, charts/vo-cutouts/templates/deployment-worker.yaml, charts/vo-cutouts/templates/deployment.yaml, charts/vo-cutouts/templates/ingress.yaml, charts/vo-cutouts/templates/networkpolicy.yaml, charts/vo-cutouts/templates/redis-networkpolicy.yaml, charts/vo-cutouts/templates/redis-service.yml, charts/vo-cutouts/templates/redis-statefulset.yaml, charts/vo-cutouts/templates/service.yaml, charts/vo-cutouts/templates/serviceaccount.yaml, charts/vo-cutouts/templates/vault-secret.yaml, charts/vo-cutouts/values.yaml
Add a new chart for the vo-cutouts service and its supporting Redis,
database worker, and cutout worker.  The cutout worker pod is based
on the stack container with Dramatiq and the cutout service deployed
dynamically on container start.
Add read:image to the Gafaelfawr list of known scopes, since it will
be used for access control for the vo-cutouts service.
=> [DM-32258] Add vo-cutouts chart

charts/kafka-connect-manager/Chart.yaml, charts/kafka-connect-manager/README.md, charts/kafka-connect-manager/templates/mirrormaker2.yaml, charts/kafka-connect-manager/values.yaml
Expose `max.request.size` configuration for Mirror Maker 2  in the Helm chart
=> [DM-32576] Fine tune replicator configuration on stable

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/README.md, charts/gafaelfawr/templates/service.yaml, charts/moneypenny/Chart.yaml, charts/moneypenny/values.yaml
Also remove the old gafaelfawr-service definition in favor of the
service named gafaelfawr.  moneypenny and one Phalanx reference
were the only uses of the old name, both of which will be fixed as
part of this deployment.
=> [DM-32520] Update to Gafaelfawr 3.3.0

charts/alert-stream-simulator/.helmignore, charts/alert-stream-simulator/Chart.yaml, charts/alert-stream-simulator/README.md, charts/alert-stream-simulator/templates/_helpers.tpl, charts/alert-stream-simulator/templates/deployment.yaml, charts/alert-stream-simulator/templates/kafka-topics.yaml, charts/alert-stream-simulator/templates/kafka-user.yaml, charts/alert-stream-simulator/templates/load-data-job.yaml, charts/alert-stream-simulator/values.yaml
Adds a new alert-stream-simulator application which publishes a static set of alerts into Kafka.
=> DM-31978: Add alert-stream-simulator

charts/alert-stream-simulator/Chart.yaml, charts/alert-stream-simulator/templates/load-data-job.yaml
Using a helm hook makes the job immediately disappear on success which makes it hard to get logs. Sync is more appropriate.
=> alert-stream-simulator: use an argo hook, not a helm hook, for job

charts/alert-stream-simulator/Chart.yaml, charts/alert-stream-simulator/templates/kafka-topics.yaml
Always delete and remake the static topic during an Argo sync so that it's always got a single copy of the simulated alert data.
=> alert-stream-simulator: force recreation of static topic

charts/alert-stream-simulator/Chart.yaml, charts/alert-stream-simulator/templates/_helpers.tpl, charts/alert-stream-simulator/templates/kafka-topics.yaml, charts/alert-stream-simulator/templates/load-data-job.yaml, charts/alert-stream-simulator/values.yaml
The Kafka topic that holds static alert data needs to be created de novo and
populated with a single pass of the sample alert data.
Populating it with data is done via a Kubernetes Job. This job runs on *every*
deployment of the simulator, which ensures that we're always using the latest
schema and alert data.
But it also means we need to delete the topic before filling it with data.
There is no clear way to signal this to Strimzi, so making it a Strimzi
KafkaTopic resource doesn't really work; instead, this revision uses a new
version of the stream simulator with configuration set to always create a new
topic, overwriting one if it already exists.
=> DM-32778: alert-stream-simulator: create static topic via job, not resource

charts/alert-stream-broker/Chart.yaml, charts/alert-stream-broker/README.md, charts/alert-stream-broker/templates/kafka.yaml, charts/alert-stream-broker/values.yaml
Pinned IP addresses for the external load balancer are necessary in order to
give the broker a public DNS record.
=> DM-32362: Permit IP address pinning for alert broker external listeners.

charts/alert-stream-broker/Chart.yaml, charts/alert-stream-broker/templates/kafka.yaml
The Bootstrap listener is using a LoadBalancer type. This means it doesn't use the 'host' field, and Strimzi errors if you try.
=> alert-stream-broker: don't set external bootstrap host

charts/alert-stream-simulator/Chart.yaml, charts/alert-stream-simulator/templates/kafka-topics.yaml, charts/alert-stream-simulator/values.yaml
The integer `604800000` gets rendered as `6.048e+08` which breaks.
=> alert-stream-simulator: fix types for very large int vals

charts/moneypenny/Chart.yaml, charts/moneypenny/README.md, charts/moneypenny/templates/deployment.yaml
Update to version 0.3.0 and include some pod metadata in a mounted
file system so that moneypenny can set owner information in created
Kubernetes objects.
=> [DM-32811] Bump Moneypenny version

charts/moneypenny/Chart.yaml, charts/moneypenny/README.md, charts/moneypenny/templates/deployment.yaml
Fixes the scheme of redirects and therefore passing of the
Authorization header to the request for commissioning status.
=> [DM-32811] Update to moneypenny 0.3.1

charts/alert-database/Chart.yaml, charts/alert-database/templates/ingester-deployment.yaml
It's 'serviceAccountName', not 'serviceAccountNane'
=> DM-32643: alert-database: fix podspec field name

charts/alert-database/Chart.yaml, charts/alert-database/ci/values-idfint.yaml, charts/alert-database/templates/_helpers.tpl, charts/alert-database/templates/ingress.yaml, charts/alert-database/templates/server-deployment.yaml, charts/alert-database/templates/server-serviceaccount.yaml, charts/alert-database/templates/service.yaml, charts/alert-database/values.yaml
Adds an HTTP server frontend to the alert database buckets.
Adds a ServiceAccount, Ingress, Service, and Deployment for accessing the data inside the alert database's buckets.
=> DM-32644: alert-database: add frontend HTTP server

charts/alert-database/Chart.yaml, charts/alert-database/README.md, charts/alert-database/templates/ingress.yaml
This was causing all requests to be redirected to the alertdb service. What I actually wanted was to rewrite requests.
=> DM-32644: alert-database: use rewrite-target, not app-root

charts/cadc-tap-postgres/Chart.yaml, charts/cadc-tap-postgres/templates/tap-ingress-anonymous.yaml, charts/cadc-tap-postgres/templates/tap-ingress-authenticated.yaml
The syntax was updated for the new apiVersion, but the apiVersion
update itself was missed.
=> [DM-32991] Fix apiVersion for cadc-tap-postgres Ingresses

charts/mobu/Chart.yaml, charts/mobu/README.md, charts/mobu/templates/statefulset.yaml
We were seeing the pod intermittently be marked as not ready even
though it seemed to be running fine.  The theory is that it was
taking longer than 1s under load.  Increase the readiness probe
timeout to 10s.
=> [DM-33222] Increase mobu readiness probe timeout

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/README.md, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/values.yaml
Allow configuring generic OpenID Connect support instead of only
using OpenID Connect for CILogon.  Add configuration parameters
for the new LDAP group support, and bump the version number.
=> [DM-33121] Add LDAP and generic OIDC support to Gafaelfawr

charts/sasquatch/Chart.yaml, charts/sasquatch/README.md, charts/sasquatch/charts/strimzi-kafka/Chart.yaml, charts/sasquatch/charts/strimzi-kafka/README.md, charts/sasquatch/charts/strimzi-kafka/templates/kafka.yaml, charts/sasquatch/charts/strimzi-kafka/templates/schema-registry-topic.yaml, charts/sasquatch/charts/strimzi-kafka/templates/schema-registry-user.yaml, charts/sasquatch/charts/strimzi-kafka/templates/schema-registry.yaml, charts/sasquatch/charts/strimzi-kafka/values.yaml, charts/sasquatch/values.yaml
- Use the schema-registry-operator to add Confluent schema registry to Sasquatch Helm chart
- Deploy the strimzi entity operator to create the schema registry topic and user
- Enable authentication and authorization
- Ingress configuration for the schema registry will be added in another PR
=> [DM-33257] Add Confluent schema registry to Sasquatch Helm chart

charts/moneypenny/Chart.yaml, charts/moneypenny/README.md, charts/moneypenny/templates/ingress.yaml, charts/moneypenny/templates/role.yaml, charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
Update for the 1.0.0 release.  Add permissions to list and watch
pods so that we can use a watch to wait for the provisioning pod
to finish.  Increase the NGINX proxy timeout to 5m plus ten seconds,
which is long enough to wait for the default timeout for a pod to
run.
=> [DM-33244] Update moneypenny chart

charts/noteburst/.gitignore, charts/noteburst/Chart.yaml, charts/noteburst/templates/configmap.yaml, charts/noteburst/values.yaml
This 0.2.0-alpha.1 release includes a redis sub-chart to begin integrating the deployment or noteburst's redis queue.
=> DM-33025: Initial redis integration for noteburst (noteburst 0.2.0-alpha.1)

charts/noteburst/Chart.yaml, charts/noteburst/README.md, charts/noteburst/templates/configmap.yaml, charts/noteburst/templates/worker-configmap.yaml, charts/noteburst/templates/worker-deployment.yaml, charts/noteburst/templates/worker-identities-configmap.yaml, charts/noteburst/values.yaml
Workers are deployed as a Deployment. The worker.identities field in values.yaml defines Science Platform identities that each worker instance can acquire at start-up.
=> DM-33025: Implement noteburst worker pool (Noteburst 0.2.0-alpha.3)

charts/cachemachine/Chart.yaml, charts/cachemachine/templates/ingress.yaml, charts/datalinker/Chart.yaml, charts/datalinker/templates/ingress.yaml, charts/datalinker/values.yaml, charts/mobu/Chart.yaml, charts/mobu/templates/ingress.yaml, charts/sherlock/Chart.yaml, charts/sherlock/templates/ingress.yaml, charts/sherlock/values.yaml, charts/times-square/Chart.yaml, charts/times-square/templates/ingress.yaml, charts/times-square/values.yaml, rsp-starter/templates/ingress.yaml
The rsp-starter and thus some of the charts incorrectly referenced
.Values.gafaelfawrAuthQuery instead of
.Values.ingress.gafaelfawrAuthQuery.
=> [DM-26506] Clean up gafaelfawrAuthQuery configuration

charts/cachemachine/Chart.yaml, charts/cachemachine/templates/networkpolicy.yaml, charts/datalinker/Chart.yaml, charts/datalinker/templates/networkpolicy.yaml, charts/mobu/Chart.yaml, charts/mobu/templates/networkpolicy.yaml, charts/moneypenny/Chart.yaml, charts/moneypenny/templates/networkpolicy.yaml, charts/sherlock/Chart.yaml, charts/sherlock/templates/networkpolicy.yaml, charts/times-square/Chart.yaml, charts/times-square/templates/networkpolicy.yaml, rsp-starter/templates/networkpolicy.yaml
A NetworkPolicy has to reference the pod port, not the service
port, and rsp-starter had this incorrect.
=> [DM-26506] Fix NetworkPolicy ports

charts/cadc-tap/Chart.yaml, charts/cadc-tap/README.md, charts/cadc-tap/templates/mock-qserv-service.yaml
This has to be called mock-qserv to match the default setting in
the values.yaml file when mock Qserv is enabled.
=> [DM-33241] Fix name of mock-qserv service

charts/cadc-tap/Chart.yaml, charts/cadc-tap/README.md, charts/cadc-tap/templates/mock-qserv-deployment.yaml, charts/cadc-tap/templates/uws-db-deployment.yaml
Run mock-qserv as root with a writable file system for now, since
the startup of its Docker image apparently requires rewriting files
in /etc (why?).  Fixing this looks like a larger issue.
Fix the user the uws-db container runs as to hopefully match the
UID and GID of the postgres user and thus solve initdb issues.
=> [DM-33241] Fix security settings for cadc-tap databases

charts/cadc-tap/Chart.yaml, charts/cadc-tap/README.md, charts/cadc-tap/templates/mock-qserv-deployment.yaml, charts/cadc-tap/templates/tap-deployment.yaml, charts/cadc-tap/templates/uws-db-deployment.yaml
The containers apparently cannot currently run with most reasonable
security settings and that will require additional work.
=> [DM-33241] Drop more security settings for cadc-tap

renovate.json
Looks like [bumpVersion](https://docs.renovatebot.com/configuration-options/#bumpversion) is the configuration we need to automatically bump the chart version.
=> [DM-33479] Make Renovate bot bump chart version automatically

charts/sasquatch/Chart.yaml, charts/sasquatch/README.md, charts/sasquatch/charts/strimzi-kafka/templates/kafka.yaml
This plain listener is going to be used to connect to Kafka from within the cluster without for clients like kafka-connect-manager and SAL Kafka producers.
=> [DM-33445] Disable TLS encryption in one of the internal listeners

charts/sasquatch/Chart.yaml, charts/sasquatch/README.md, charts/sasquatch/values.yaml
- Add `kafka-connect-manager` as a dependency of the sasquatch chart.
- Initial configuration to deploy the InfluxDB Sink connector.
=> [DM-33392] Add kafka-connect-manager subchart to Sasquatch

charts/gafaelfawr/templates/configmap.yaml
`redirect_url` is a required parameter for gafaelfawr config. this patch adds this to the oidc configuration.
=> fix: ensure redirect_url present for oidc

charts/gafaelfawr/templates/configmap.yaml
gafaelfawr expects `ldap.base_dn` rather than `ldap.baseDn`. this patch changes the key to use underscore rather than camelcase.
```
Traceback (most recent call last):
File "/opt/venv/bin/gafaelfawr", line 8, in <module>
sys.exit(main())
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 754, in …
```
=> fix: underscore for ldap base_dn

charts/sasquatch/Chart.yaml, charts/sasquatch/README.md, charts/sasquatch/values.yaml
- This should be handled as a secret instead. 
- The Kapacitor Helm chart has the `existingSecret` parameter that could be used to populate the KAPACITOR_SLACK_URL env variable. I'm removing the slack webook from for now and will open a PR upstream to add this variable to the Kapacitor secret.
=> Do not publish the Sasquatch slack webhook in the chart configuration

charts/vo-cutouts/Chart.yaml, charts/vo-cutouts/README.md, charts/vo-cutouts/templates/configmap.yaml, charts/vo-cutouts/values.yaml
The same service account used for CloudSQL will also be used to
access GCS, and must be passed down to the application for GCS URL
signing.
=> [DM-33513] Pass the Google service account to vo-cutouts

charts/exposurelog/Chart.yaml, charts/exposurelog/templates/ingress.yaml
The latest ingress-nginx controller requires an explicit annotation
for ingresses that it should pick up.
=> Add nginx annotation to exposurelog ingress

charts/narrativelog/Chart.yaml, charts/narrativelog/templates/ingress.yaml
Provide a default path while still allowing it to be overridden.
Ditch the unnecessary fullName variable (copying the way moneypenny does it).
Bump the chart version a lot because it seems we are likely close now.
=> narrativelog: improve ingress

charts/vo-cutouts/Chart.yaml, charts/vo-cutouts/README.md, charts/vo-cutouts/templates/configmap.yaml, charts/vo-cutouts/templates/db-worker-deployment.yaml, charts/vo-cutouts/templates/ingress.yaml, charts/vo-cutouts/templates/worker-deployment.yaml, charts/vo-cutouts/values.yaml
This is a long list of small changes, which can be reviewed commit by commit if desired.
- Spawn a single database worker process per pod. If we want to scale horizontally, we'll add more pods
- Default to a couple of cutout worker backends, since they are now limited to one process and thread per pod
- Set the vo-cutouts logging style to production for JSON logs
- Align the job lifetime with the bucket lifetime (set to 30 days)
- Stop doing path rewriting in the ingress since the application now exposes `/api/cutout` routes
- Simplify how the permissions on the PostgreSQL secret for the worker backend are fixed
- Use the pre-built worker backend instead of constructing it on the fly during pod startup
=> [DM-33604] Cleanup and improvements for vo-cutouts chart

charts/vo-cutouts/Chart.yaml, charts/vo-cutouts/values.yaml
Otherwise, Helm turns it into a floating point number, which then
breaks the application.
=> [DM-33720] Quote vo-cutouts job lifetime

charts/vo-cutouts/Chart.yaml, charts/vo-cutouts/templates/deployment.yaml, charts/vo-cutouts/templates/worker-deployment.yaml
The application now expects the /api prefix. The secrets now need to be world-readable.
=> Fix the vo-cutouts readiness probe URL, secret permissions

charts/cachemachine/Chart.yaml, charts/nublado2/Chart.yaml, charts/nublado2/values.yaml
JH 2.1.1 plus custom (asyncio) kubespawner, plus culler-enabling with long timeout to prepare for Dan's culler rework.
=> tickets/DM-33044: adopt JH 2.x

charts/gafaelfawr/Chart.yaml, charts/gafaelfawr/templates/configmap.yaml, charts/gafaelfawr/values.yaml
Add Helm configuration to retrieve the user's UID via LDAP instead
of from an OpenID Connect JWT.  Update the application verison to
3.6.0.
=> [DM-33718] Add Gafaelfawr support for UID via LDAP

charts/times-square/Chart.yaml, charts/times-square/README.md, charts/times-square/serviceaccount.yaml, charts/times-square/values.yaml
Fixes for the times-square chart:
- add ServiceAccount template to support Cloud SQL
- Update name of TS's Docker image
=> DM-33627: Times Square 0.1.6 chart fixes

charts/sherlock/Chart.yaml, charts/sherlock/templates/deployment.yaml, charts/sherlock/values.yaml
This allows for the configuration of the publish URL for
sherlock to publish its status to.
=> [DM-34074] Ability to set publish URL

charts/sherlock/Chart.yaml, charts/sherlock/templates/ingress.yaml
Okay so this should inject the cors headers, and I'll get rid of the
code that generates the cors headers from the sherlock code.
Unfortunately, setting the list of domains doesn't seem to work.
This means that I can't set the host to just status.lsst.codes, instead
the default is *, which isn't great, but isn't terrible.
nginx.ingress.kubernetes.io/cors-allow-origin is the annotation
that is supposed to work, but when I set it it does not work.
=> [DM-34433] Sherlock: Set cors headers

charts/redis/Chart.yaml, charts/redis/templates/statefulset.yaml
It looks like the StatefulSet always prepends its own name to the storage, so avoid repeating that name and make the PVC name shorter.
=> DM-37390: Simplify Redis persistent storage name

charts/redis/Chart.yaml, charts/redis/templates/statefulset.yaml
I renamed the volume template but not the reference to it.
=> DM-37390: Fix Redis StatefulSet volume reference

charts/redis/Chart.yaml, charts/redis/templates/statefulset.yaml
If no persistence is enabled, don't bother enabling the append storage mechanism.  Fix the name of the volume used in cases where we're not creating a new PVC as part of the StatefulSet.
=> DM-37390: Improvements for non-persistent Redis

.github/workflows/release.yaml
We should no longer need a separate service account and token for releasing charts and should instead be able to use the default GITHUB_TOKEN secret.
=> DM-37528: Use GITHUB_TOKEN for chart releasing

charts/redis/Chart.yaml, charts/redis/README.md, charts/redis/values.yaml
Move the tag of the Redis version to install into values.yaml so that Renovate will update it for us automatically.  appVersion isn't checked or understood by Renovate.
=> DM-37516: Don't use appVersion for redis chart

charts/strimzi-registry-operator/Chart.yaml, charts/strimzi-registry-operator/README.md, charts/strimzi-registry-operator/crds/registry.yaml
- spec.preserveUnknownFields has been deprecated in apiextensions.k8s.io/v1
- Bump chart version to 2.1.2
=> [DM-52270] Remove deprecated field in CRD spec
